[package]
name = "rasterizer-jni"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
rasterizer = { path = "../rasterizer" }
ultraviolet = "0.9.0"

[features]
stats = ["rasterizer/stats"]